//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiderPlugin.UnrealLink.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RiderPlugin.UnrealLink.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract RiderLink in Engine.
        /// </summary>
        internal static string ExtractRiderLinkInEngine_Text {
            get {
                return ResourceManager.GetString("ExtractRiderLinkInEngine_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract RiderLink in Game.
        /// </summary>
        internal static string ExtractRiderLinkInGame_Text {
            get {
                return ResourceManager.GetString("ExtractRiderLinkInGame_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract RiderLink plugin into the Engine in the Solution.
        ///Note: Use it for Unreal Engine version built from source only. It will not work with UE4 and UE5 from Epic Games Launcher.
        ///Use this option if installation of RiderLink plugin fails for some reason..
        /// </summary>
        internal static string ExtractRiderLinkPluginInEngineDescription_Text {
            get {
                return ResourceManager.GetString("ExtractRiderLinkPluginInEngineDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract RiderLink plugin into every Game available in the Solution.
        ///Note: It will not try to build RiderLink for your current project.
        ///Use this option if installation of RiderLink plugin fails for some reason..
        /// </summary>
        internal static string ExtractRiderLinkPluginInGameDescription_Text {
            get {
                return ResourceManager.GetString("ExtractRiderLinkPluginInGameDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this option is enabled, the RiderLink editor plugin will be automatically updated..
        /// </summary>
        internal static string IfThisOptionIsEnabledTheRiderLinkEditor_Text {
            get {
                return ResourceManager.GetString("IfThisOptionIsEnabledTheRiderLinkEditor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install RiderLink in Engine.
        /// </summary>
        internal static string InstallRiderLinkInEngine_Text {
            get {
                return ResourceManager.GetString("InstallRiderLinkInEngine_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install RiderLink in Game.
        /// </summary>
        internal static string InstallRiderLinkInGame_Text {
            get {
                return ResourceManager.GetString("InstallRiderLinkInGame_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install RiderLink plugin into the Engine. Doesn&apos;t work with UE5 from Epic Games Launcher..
        /// </summary>
        internal static string InstallRiderLinkPluginInEngineDescription_Text {
            get {
                return ResourceManager.GetString("InstallRiderLinkPluginInEngineDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install RiderLink plugin into every Game available in the Solution. If Rider will fail to install RiderLink plugin to any of the Game projects, It&apos;ll revert the installation process..
        /// </summary>
        internal static string InstallRiderLinkPluginInGameDescription_Text {
            get {
                return ResourceManager.GetString("InstallRiderLinkPluginInGameDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation is in progress....
        /// </summary>
        internal static string RiderLinkInstallationIsInProgress_Text {
            get {
                return ResourceManager.GetString("RiderLinkInstallationIsInProgress_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnrealLink plugin settings.
        /// </summary>
        internal static string UnrealLinkPluginSettings_Text {
            get {
                return ResourceManager.GetString("UnrealLinkPluginSettings_Text", resourceCulture);
            }
        }
    }
}
