name: CI

on:
  push:
    branches: [ net201 ]
  pull_request:
    branches: [ net201 ]

jobs:
  build:
    env:
      working-dir: ${{ github.workspace}}${{ matrix.config.SEP }}rd-cpp
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest", artifact: "UnrealLink-Windows",
            os: windows-latest,
            SEP: \
          }

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Hack Generate common model
      run: gradlew.bat generateUE4Lib
      shell: cmd
    - name: Hack Generate Unreal Editor<>Rider model
      run: gradlew.bat generateEditorPluginModel
      shell: cmd
    - name: Hack Clean files in model
      run: git reset --hard
    - name: Build Plugin
      run: gradlew.bat buildPlugin -PBuildCounter=${{ github.run_number }} -PConfiguration=Release
      shell: cmd
    - name: Upload built plugin
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.config.artifact }}
        path: output/*
